if(NOT DEFINED WAYDISPLAY_SOURCE_DIR)
    message(FATAL_ERROR "WAYDISPLAY_SOURCE_DIR is required")
endif()

set(_stream_source "${WAYDISPLAY_SOURCE_DIR}/src/server/wd_stream.c")
file(READ "${_stream_source}" _content)

if(NOT _content MATCHES "struct wd_buffer\\*[ \t\r\n]+encoded_payload")
    message(FATAL_ERROR "tile delivery must own its encoded payload explicitly")
endif()
if(NOT _content MATCHES "struct wd_buffer\\*[ \t\r\n]+payload;")
    message(FATAL_ERROR "parallel tile encode results must use shared buffer ownership")
endif()
if(NOT _content MATCHES "wd_async_udp_send_packet_owned[ \t\r\n]*\\(")
    message(FATAL_ERROR "tile UDP delivery must retain payload storage through io_uring completion")
endif()
if(_content MATCHES "free[ \t\r\n]*\\([ \t\r\n]*delivery->encoded_payload")
    message(FATAL_ERROR "tile delivery regressed to raw malloc/free payload ownership")
endif()
