# Keep labels tied to the scope actually counted and document the CLI policy.
if(NOT DEFINED WAYDISPLAY_SOURCE_DIR)
    message(FATAL_ERROR "WAYDISPLAY_SOURCE_DIR is required")
endif()

file(READ "${WAYDISPLAY_SOURCE_DIR}/src/server/wd_stream_telemetry.c" server_log)
file(READ "${WAYDISPLAY_SOURCE_DIR}/src/client/client_telemetry.cpp" client_log)
file(READ "${WAYDISPLAY_SOURCE_DIR}/docs/command-line.md" cli_guide)
file(READ "${WAYDISPLAY_SOURCE_DIR}/docs/architecture.md" architecture)
file(READ "${WAYDISPLAY_SOURCE_DIR}/include/waydisplay/wd_config.h" config)

foreach(token IN ITEMS
    "compositor-capture/interval:" "encode_total_ms=" "configured_bitrate_kib_per_sec="
    "x11_surface_commits=" "x11_committed_bounds_mpix="
    "x11_maps=" "x11_unmaps=" "x11_configures="
    "scene_build_calls=" "scene_build_avg_ms="
    "texture_read_calls=" "texture_read_area_mpix="
    "texture_read_avg_ms=" "texture_read_failures=" "buffer_data_fallbacks=")
    string(FIND "${server_log}" "${token}" index)
    if(index EQUAL -1)
        message(FATAL_ERROR "Missing or renamed capture log token: ${token}")
    endif()
endforeach()

foreach(group IN ITEMS audio udp udp-invalid udp-async repair input video
                       tcp-async latency render)
    string(FIND "${client_log}" "client-${group}/interval:" index)
    if(index EQUAL -1)
        message(FATAL_ERROR "Missing canonical client stats group client-${group}/interval:")
    endif()
endforeach()

foreach(text IN ITEMS "${server_log}" "${client_log}")
    if(text MATCHES "wine[-_]capture|/min:|legacy_rx=")
        message(FATAL_ERROR "Obsolete or misleading capture/client log name")
    endif()
endforeach()

# These are *documented defaults*, not policy overrides: keep their numbers in sync.
string(REGEX MATCH "#define WD_VIDEO_MIN_DIRTY_PERCENT_DEFAULT[ ]+([0-9]+)u" entry "${config}")
set(entry_percent "${CMAKE_MATCH_1}")
string(REGEX MATCH "#define WD_VIDEO_EXIT_DIRTY_PERCENT_DEFAULT[ ]+([0-9]+)u" exit "${config}")
set(exit_percent "${CMAKE_MATCH_1}")
if(entry_percent STREQUAL "" OR exit_percent STREQUAL "")
    message(FATAL_ERROR "Video policy default was renamed; update the naming contract")
endif()
foreach(document IN ITEMS "${cli_guide}" "${architecture}")
    if(NOT document MATCHES "${entry_percent}%")
        message(FATAL_ERROR "Entry threshold documentation is not current")
    endif()
    if(NOT document MATCHES "${exit_percent}%")
        message(FATAL_ERROR "Exit threshold documentation is not current")
    endif()
endforeach()
# Accepted spellings and help output must agree; old flags have no alias path.
file(READ "${WAYDISPLAY_SOURCE_DIR}/src/client/client_cli.cpp" client_cli)
file(READ "${WAYDISPLAY_SOURCE_DIR}/src/server/wd_server_cli.c" server_cli)
file(READ "${WAYDISPLAY_SOURCE_DIR}/src/client/main_sdl.cpp" client_help)
file(READ "${WAYDISPLAY_SOURCE_DIR}/src/server/main_wlroots.c" server_help)
foreach(flag IN ITEMS --session-fps --display-size --link-cap-kib-per-sec --video-mode --video-codec --video-decoder)
    foreach(source IN ITEMS "${client_cli}" "${client_help}" "${cli_guide}")
        string(FIND "${source}" "${flag}" index)
        if(index EQUAL -1)
            message(FATAL_ERROR "Client parser/help/docs missing ${flag}")
        endif()
    endforeach()
endforeach()
foreach(flag IN ITEMS --listen-ipv4 --tcp-port --launch-command --display-size --output-scale --compositor-renderer --video-encoder)
    foreach(source IN ITEMS "${server_cli}" "${server_help}" "${cli_guide}")
        string(FIND "${source}" "${flag}" index)
        if(index EQUAL -1)
            message(FATAL_ERROR "Server parser/help/docs missing ${flag}")
        endif()
    endforeach()
endforeach()
foreach(source IN ITEMS "${client_cli}" "${client_help}" "${server_cli}" "${server_help}")
    if(source MATCHES "--fps[^a-z-]|--rate-kib[^a-z-]|--video-decode[^a-z-]|--listen[^a-z-]|--port[^a-z-]|--app[^a-z-]")
        message(FATAL_ERROR "An obsolete CLI name is still accepted or printed")
    endif()
endforeach()
file(READ "${WAYDISPLAY_SOURCE_DIR}/include/waydisplay/wd_protocol.h" protocol)
file(READ "${WAYDISPLAY_SOURCE_DIR}/src/server/wd_stream.c" stream)
file(READ "${WAYDISPLAY_SOURCE_DIR}/src/client/client_net.cpp" client_network)
foreach(source IN ITEMS "${protocol}" "${stream}" "${client_network}")
    if(source MATCHES "udp_rate_cap_kib_per_second|requested_capture_fps")
        message(FATAL_ERROR "Misleading legacy wire/session identifier remains")
    endif()
endforeach()
message(STATUS "CLI, wire, interval log and documented threshold names agree")
